services:
  - type: web
    name: healthyhearts-web
    env: node
    plan: free
    buildCommand: "NPM_CONFIG_PRODUCTION=false npm install && npm run build"
    startCommand: "npm run start"
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    region: frankfurt
